---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Astrea
description: Astrea - a clean and minimal, yet highly usable operating system designed as the base to be built on top of.

base-image: quay.io/fedora/fedora-silverblue:latest
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: dnf
    install:
      packages:
        - ludica
    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - nautilus
        - gnome-disks
        - gnome-software

  - type: signing
