---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: astrea
description: Astrea - a clean and minimal, yet highly usable operating system.

base-image: quay.io/fedora/fedora-silverblue
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - udica
    remove:
      packages:
        - gnome-tour
        - gnome-help
        - gnome-software
        - gnome-disk-utility
        - gnome-system-monitor
        - gnome-control-center
        - firefox
        - firefox-langpacks
        - nautilus
        - toolbox

  - type: default-flatpaks@v1
    system:
        remove:
          - org.fedoraproject.MediaWriter
          - org.gnome.Calculator
          - org.gnome.Characters
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.Extensions
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gnome.font-viewer

  - type: signing
